add_newline = true
format = """
$username\
$hostname\
$localip\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
${custom.git_branch}\
${custom.git_commit}\
${custom.git_state}\
${custom.git_metrics}\
${custom.git_status}\
${custom.jj}\
$hg_branch\
$pijul_channel\
$docker_context\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$direnv\
$env_var\
$crystal\
$sudo\
$fill\
$aws\
$azure\
$gcloud\
$container\
$shell\
$shlvl\
$cmd_duration\
$time\
$line_break\
$battery\
$status\
$os\
$jobs\
$character\
"""

[aws]
format = "[$symbol(|$profile)(|$region)(|$duration)]($style) "
symbol = " "

[aws.region_aliases]
us-east-1 = "use1"
us-east-2 = "use2"
us-west-1 = "usw1"
us-west-2 = "usw2"

[character]
error_symbol = "[λ](bold red)"
success_symbol = "[λ](bold blue)"

[container]
style = "purple"

[jobs]
# For some reason the job number is off by one in nushell, so the symbol would appear and the number
# of jobs would be shown as 2, even if there was just one frozen job. So for now we set the
# symbol_threshold to 2.
symbol_threshold = 2
number_threshold = 20
format = '[$symbol$number]($style)'

[custom.jj]
ignore_timeout = true
description = "The current jj status"
detect_folders = [".jj"]
when = "jj --ignore-working-copy root"
style = "blue"
format = "[$symbol$output ](blue)"
symbol = " "
command = '''
jj log -r @ --no-graph --limit 1 --color always --template '
  separate(" ",
    if(empty, "∅"),
    coalesce(
      truncate_end(40, description.first_line(), "…"),
      "(no desc)",
    ),
    if(bookmarks, bookmarks)
  )'
'''
# command = '''
# jj log --revisions @ --no-graph --ignore-working-copy --color always --limit 1 --template '
#   separate(" ",
#     stringify(change_id.shortest(6)),
#     bookmarks,
#     "|",
#     concat(
#       if(conflict, "💥"),
#       if(divergent, "🚧"),
#       if(hidden, "👻"),
#       if(immutable, "🔒"),
#     ),
#     if(empty, "(empty)"),
#     coalesce(
#       truncate_end(29, description.first_line(), "…"),
#       "(no desc) ",
#     ),
#   )
# '
# '''
# optionally disable git modules when JJ is found.
# note that you'll need to add ${custom.git_branch}, ${custom.git_commit} etc
# into format: https://starship.rs/config/#default-prompt-format

[git_status]
disabled = true

[custom.git_status]
shell = "bash"
when = "! jj --ignore-working-copy root"
command = "starship module git_status"
description = "Only show git_status if we're not in a jj repo"

[git_state]
disabled = true

[custom.git_state]
shell = "bash"
when = "! jj --ignore-working-copy root"
command = "starship module git_state"
description = "Only show git_status if we're not in a jj repo"

[git_commit]
disabled = true

[custom.git_commit]
shell = "bash"
when = "! jj --ignore-working-copy root"
command = "starship module git_commit"
description = "Only show git_commit if we're not in a jj repo"

[git_metrics]
disabled = true

[custom.git_metrics]
shell = "bash"
when = "! jj --ignore-working-copy root"
command = "starship module git_metrics"
description = "Only show git_metrics if we're not in a jj repo"

[git_branch]
disabled = true

[custom.git_branch]
shell = "bash"
when = "! jj --ignore-working-copy root"
command = "starship module git_branch"
description = "Only show git_branch if we're not in a jj repo"
# symbol = ""

[direnv]
disabled = true

[docker_context]
symbol = " "

[elixir]
style = "#5e3f9e"
symbol = " "

[elm]
symbol = " "

[fill]
symbol = " "

# [git_branch]
# symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[line_break]
disabled = false

[lua]
symbol = " "

[python]
symbol = " "

[rlang]
style = "blue bold"
symbol = "  "

[rust]
symbol = " "

[shell]
disabled = false
style = "bold"

[shlvl]
disabled = false
format = "($shlvl) "
style = "bold"
symbol = ""
threshold = 4

[time]
disabled = false
format = " [$time]($style) "
style = "blue"

[zig]
symbol = " "
