#!/usr/bin/env bash
set -e          # Exit if one of commands exit with non-zero exit code
set -u          # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error
set -o pipefail # Any command failed in the pipe fails the whole pipe
# set -x # Print shell commands as they are executed (or you can try -v which is less verbose)

# cb is a shorthand for "ClipBoard"
isMacOs() {
  [[ "$OSTYPE" == "darwin"* ]]
}

isWayland() {
  command -v wl-copy 2>&1 >/dev/null
}

paste() {
  if isMacOs; then
    pbpaste
  else
    if isWayland; then
      wl-paste
    else
      xsel -ob
    fi
  fi
}

copy() {
  if isMacOs; then
    pbcopy
  else
    if isWayland; then
      wl-copy
    else
      xclip -selection clipboard
    fi
  fi
}

if [ $# -eq 1 ]; then
  readlink -f "$1" | xargs echo -n | copy
elif [ ! -t 0 ]; then # If stdin descriptor isn't opened on tty (it can be interpreted as "something is piped into the stdin")
  copy
else
  paste
fi
