limit = 0

[revisions]
template = 'custom_log_oneline'
# template = 'builtin_log_oneline'

[suggest]
[suggest.exec]
mode = "fuzzy" # Accepted values: "off" (default), "regex", "fuzzy".

[preview]
revision_command = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  """jj show --summary --color always --git -r $change_id | delta --side-by-side --width $preview_width""",
]
file_command = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  """jj diff --color always --git -r $change_id '$file' | delta --side-by-side --width $preview_width""",
]
# oplog_command = [
#   "op",
#   "show",
#   "$operation_id",
#   "--color",
#   "always",
#   "--tool",
#   "difft",
# ]
show_at_start = false
position = "bottom"
width_percentage = 50.0
width_increment_percentage = 5.0

[oplog]
limit = 200

[graph]
batch_size = 50

[ui]
# theme = "my-tokyonight"
# theme = "base24-tokyo-night-dark"
auto_refresh_interval = 0
flash_message_display_seconds = 0
