return {
  {
    "nvim-treesitter/nvim-treesitter-context",
    enabled = false,
  },
  {
    "nvim-treesitter/nvim-treesitter",
    dependencies = "nushell/tree-sitter-nu",
    opts = {
      highlight = { enable = true },
      indent = { enable = true },
      rainbow = { enable = true },
      ensure_installed = {
        "bash",
        "c",
        "css",
        "dockerfile",
        "elixir",
        "fish",
        "gitcommit",
        "gitignore",
        "heex",
        "html",
        "javascript",
        "jsdoc",
        "json",
        "jsonc",
        "lua",
        "luadoc",
        "luap",
        "markdown",
        "markdown_inline",
        "nix",
        "nu",
        "python",
        "query",
        "regex",
        "svelte",
        "toml",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "yaml",
      },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "<C-space>",
          node_incremental = "<C-space>",
          scope_incremental = false,
          node_decremental = "<bs>",
        },
      },
    },
  },

  {
    "IndianBoy42/tree-sitter-just",
    enabled = true,
  },
}
