require("plugins.snacks")

require("plugins.ai")
require("plugins.colorcolumn")
require("plugins.colors")
require("plugins.completion")
require("plugins.flash")
require("plugins.formatting")
require("plugins.join")
require("plugins.kitty")
require("plugins.lsp")
-- require("plugins.lsp_1")
require("plugins.lualine")
require("plugins.markdown")
require("plugins.misc")
require("plugins.multicursors")
require("plugins.oil")
require("plugins.quickfix")
require("plugins.surround")
require("plugins.text-objects")
require("plugins.treesitter")
require("plugins.vcs")
require("plugins.visual-whitespace")
require("plugins.which-key")
require("plugins.yazi")
