--when.repositories = ["~/mh"]

[user]
email = "brian.bonsignore@i-qlair.com"

# Configure signing backend as before, but lazily signing only on push.
[signing]
behavior = "drop"
backend = "ssh"
backends.ssh.program = "/opt/1Password/op-ssh-sign"
backends.ssh.allowed-signers = "~/oiolosse/home-manager/bbonsign/modules/programs/git/allowed_signers"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKSFThjipGc4GEwPZD8uPgdeIf23SBJcv++8kfAaPqY5"

[git]
sign-on-push = true
