configpath: /var/home/bbonsign/.config/nom/config.yml
version: ""
feeds:
    - url: https://lucumr.pocoo.org/feed.xml
      name: Armin Ronacher
    - url: https://bower.sh/rss
      name: Eric Bower (Erock), zmx dev
    - url: https://ersc.io/rss.xml
      name: ersc
    - url: https://willhbr.net/feed.xml
      name: Will Richardson
    - url: https://oseifert.ch/blog/rss.xml
      name: Oliver Seifert
    - url: https://duckdb.org/feed.xml
      name: DuckDB
    - url: https://jakelazaroff.com/rss.xml
      name: Jake Lazaroff
    - url: https://darryl-ruggles.cloud/feed.xml
      name: Darryl's World of Cloud
    - url: https://distantprovince.by/rss.xml
      name: Distant Province - Alex Martsinovich
    - url: https://nvim-mini.org/blog/index.xml
      name: Nvim-Mini
    - url: https://wickstrom.tech/feed.xml
      name: Oskar Wickström
    - url: https://obsidian.md/feed.xml
      name: Obsidian Blog
    - url: https://www.germanvelasco.com/feed.xml
      name: German Velasco
    - url: https://noctalia.dev/rss.xml
      name: Noctalia
    - url: https://ampcode.com/news.rss
      name: Amp
    - url: https://kristoff.it/index.xml
      name: Loris Cro
    - url: https://neovim.io/news.xml
      name: Neovim
database: nom.db
ordering: desc
filtering:
    defaultIncludeFeedName: false
theme:
    glamour: tokyo-night
    titleColor: "62"
    titleColorFg: "231"
    filterColor: "62"
    selectedItemColor: "170"
    readIcon: ✓
http:
    mintls: TLS 1.2
